# Generated by Django 4.1.5 on 2023-01-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFormTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_pressure', models.PositiveSmallIntegerField()),
                ('knee_pain', models.BooleanField()),
                ('last_physical_labor', models.DateField()),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_two', to='medical_record.medicalrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalFormOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headache', models.BooleanField()),
                ('nicotine_or_alcohol', models.BooleanField()),
                ('sport', models.BooleanField()),
                ('temperature', models.PositiveSmallIntegerField()),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_one', to='medical_record.medicalrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
