# Generated by Django 4.1.5 on 2023-01-03 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('medical_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalformone',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forms_one', to='doctor.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalformtwo',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forms_two', to='doctor.doctor'),
            preserve_default=False,
        ),
    ]
