# Generated by Django 4.1.5 on 2023-01-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='adult',
            field=models.BooleanField(default=False),
        ),
    ]
