# Generated by Django 4.1.5 on 2023-01-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0002_medicalrecord_adult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='adult',
        ),
    ]
